// generated by stringer -type=Token; DO NOT EDIT

package parse

import "fmt"

const _Token_name = "ILLEGALEOFWSIDENTLEFTBRACERIGHTBRACELEFTSQBRACERIGHTSQBRACECOLONCOMMANUMERICMODELFIELDSPAGINATIONSTRINGINTDOUBLEDATEDATETIME"

var _Token_index = [...]uint8{0, 7, 10, 12, 17, 26, 36, 47, 59, 64, 69, 76, 81, 87, 97, 103, 106, 112, 116, 124}

func (i Token) String() string {
	if i < 0 || i+1 >= Token(len(_Token_index)) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
